'use strict';

/* eslint-disable id-length */

module.exports = {
  accounts: [
    'deleteAccount',
    'deleteScreenSet',
    'finalizeRegistration',
    'getAccountInfo',
    'getConflictingAccount',
    'getCounters',
    'getPolicies',
    'getProfilePhoto',
    'getRegisteredCounters',
    'getSchema',
    'getScreenSets',
    'importProfilePhoto',
    'incrementCounters',
    'initRegistration',
    'isAvailableLoginID',
    'linkAccounts',
    'login',
    'logout',
    'notifyLogin',
    'publishProfilePhoto',
    'register',
    'registerCounters',
    'resendVerificationCode',
    'resetPassword',
    'search',
    'setAccountInfo',
    'setPolicies',
    'setProfilePhoto',
    'setSchema',
    'setScreenSet',
    'socialLogin',
    'unregisterCounters',
    'uploadProfilePhoto',
    'tfa.deactivateProvider',
    'tfa.finalizeTFA',
    'tfa.getCertificate',
    'tfa.getProviders',
    'tfa.initTFA',
    'tfa.unregisterDevice',
  ],

  comments: [
    'analyzeMediaItem',
    'deleteComment',
    'flagComment',
    'getCategories',
    'getCategoryInfo',
    'getComments',
    'getRelatedUsers',
    'getStreamInfo',
    'getTopRatedStreams',
    'getTopStreams',
    'getUserComments',
    'getUserHighlighting',
    'getUserOptions',
    'highlightUser',
    'moveComments',
    'postComment',
    'getCategoryInfo',
    'setStreamInfo',
    'setUserOptions',
    'subscribe',
    'unsubscribe',
    'updatedComment',
    'vote',
  ],

  ds: ['delete', 'get', 'getSchema', 'setSchema', 'search', 'store'],

  fidm: [
    'saml.delIdP',
    'saml.getConfig',
    'saml.getRegisteredIdPs',
    'saml.importIdPMetadata',
    'saml.registerIdP',
    'saml.setConfig',
  ],

  ids: [
    'deleteAccount',
    'getAccountInfo',
    'getCounters',
    'getRegisteredCounters',
    'getSchema',
    'incrementCounters',
    'registerCounters',
    'search',
    'setAccountInfo',
    'setSchema',
    'unregisterCounters',
  ],

  gm: [
    'deleteAction',
    'deleteChallenge',
    'deleteChallengeVariant',
    'getActionConfig',
    'getActionsLog',
    'getChallengeConfig',
    'getChallengeStatus',
    'getChallengeVariant',
    'getGlobalConfig',
    'getTopUsers',
    'notifyAction',
    'redeemPoints',
    'resetLevelStatus',
    'setAccountConfig',
    'setChallengeConfig',
    'setGlobalConfig',
  ],

  reports: [
    'getAccountsStats',
    'getChatStats',
    'getCommentsStats',
    'getFeedStats',
    'getGMStats',
    'getGMTopUsers',
    'getGMUserStats',
    'getIRank',
    'getReactionsStats',
    'getSocializeStats',
  ],

  socialize: [
    'checkin',
    'deleteAccount',
    'delUserSettings',
    'exportUsers',
    'facebookGraphOperation',
    'getAlbums',
    'getContacts',
    'getFeed',
    'getFriendsInfo',
    'getPhotos',
    'getPlaces',
    'getRawData',
    'getReactionsCount',
    'getSessionInfo',
    'getTopShares',
    'getUserInfo',
    'getUserSettings',
    'incrementReactionsCount',
    'logout',
    'notifyLogin',
    'notifyRegistration',
    'publishUserAction',
    'removeConnection',
    'sendNotification',
    'setStatus',
    'setUID',
    'setUserInfo',
    'setUserSettings',
    'shortenURL',
  ],

  gcs: ['deleteObjectData', 'deleteUserData', 'getobjectData', 'getUserData', 'search', 'setObjectData', 'setUserData'],
};
